CREATE DATABASE IF NOT EXISTS `tanarok` CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci;
USE `tanarok`;
DROP TABLE IF EXISTS `adatok`;
CREATE TABLE `adatok` (
  `AZON` INT NOT NULL AUTO_INCREMENT,
  `NEV` VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci NOT NULL,
  `SZAK` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_hungarian_ci,
  `METTOL` INT,
  `MEDDIG` INT,
  PRIMARY KEY (`AZON`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;
SELECT NEV FROM adatok WHERE METTOL IN (1986, 1987);
SELECT NEV, SZAK FROM adatok WHERE SZAK LIKE '%matematika%' ORDER BY METTOL ASC;
SELECT NEV, SZAK, (MEDDIG - METTOL) AS Evek FROM adatok;
SELECT NEV, (MEDDIG - METTOL) AS Evek FROM adatok ORDER BY Evek DESC LIMIT 1;
INSERT INTO adatok (NEV, SZAK, METTOL, MEDDIG) VALUES ('Tóth Antal','kémia-fizika',2000,2005);